### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by a3s7p**
- refactor appliance scripts towards a more declarative structure
- drop async_trait dep

### CODE REVIEW

**Comment by JedMeister** [comment]
Hey man, I tried building this (i.e. via `cargo build`) and I get errors like this (this is the last 2 and the trailing text):
```
error[E0446]: private type `App` in public interface
  --> src/apps/suitecrm/mod.rs:5:1
   |
5  | pub const APP: App = App {
   | ^^^^^^^^^^^^^^^^^^ can't leak private type
   |
  ::: src/apps/mod.rs:94:1
   |
94 | struct App {
   | ---------- `App` declared as private

error[E0446]: private type `App` in public interface
  --> src/apps/wordpress/mod.rs:5:1
   |
5  | pub const APP: App = App {
   | ^^^^^^^^^^^^^^^^^^ can't leak private type
   |
  ::: src/apps/mod.rs:94:1
   |
94 | struct App {
   | ---------- `App` declared as private

For more information about this error, try `rustc --explain E0446`.
error: could not compile `clicksnap` (bin "clicksnap") due to 43 previous errors
```

**Comment by a3s7p** [comment]
@JedMeister thanks for the feedback! it compiles fine on nightly rust — should have tested with stable, my bad. fixed now.

tested to work with:

```
cargo 1.72.1 (103a7ff2e 2023-08-15)
rustc 1.72.1 (d5c2e9c34 2023-09-13)
```

**Review by OnGle — APPROVED** [review]
Looks awesome, really excited about this, opens us up to later being able to both have more granular reuse but also potentially tighter feedback loop when working on particularly stubborn screenshots. And the more detailing output on each step is awesome! :+1: :+1: :+1:

**Comment by JedMeister** [comment]
Ok, merging this now... :grin:

**Pull request merged**
