### PR TITLE
Add generic gameserver screenshots (no web ui)

### PR DESCRIPTION
**Pull request by JedMeister**
As per subject.

### CODE REVIEW

**Review by OnGle — CHANGES_REQUESTED** [review]
Missing the `src/apps/gameserver/gameserver.mod`. If you want an example of an empty screenshot, the NodeJS one is the most succinct.

**Comment by JedMeister** [comment]
I ended up just copying mumble. I haven't tested but it looks pretty generic and mumble worked ok!?

**Review by OnGle — APPROVED** [review]
Lgtm :+1:

**Comment by OnGle** [comment]
For what it's worth

```rust
pub const APP: App = App {
    test: &[
    ],
    ..App::default()
};
```

Just means to to set the values for everything other than `test` (which is sets to an empty slice) to the corrosponding values specified in `App::default()`. However the default value for test is an empty slice so it's equivalent to

```rust
pub const APP: App = App {
    ..App::default()
};
```

But if all values are the same as `App::default()` then you can simplify again too:
```rust
pub const APP: App = App::default();
```

But it doesn't really matter, you copied from mumble and I never bothered to clean up that at the time, we can do that later.

**Comment by JedMeister** [comment]
Awesome, thanks man! :)

**Pull request merged**
