### PR TITLE
Add gitea

### PR DESCRIPTION
**Pull request by OnGle**
Adds support for screenshotting gitea.

### CODE REVIEW

**Review by Christie018 — APPROVED** [review]
Code changes to update the clicksnap tool for the gitea appliance look good to me 👍🏾

**Comment by a3s7p** [comment]
@OnGle this needs a rebase :slightly_smiling_face:

**Comment by OnGle** [comment]
@a3s7p should be good now :+1:

**Review by a3s7p — APPROVED** [review]
lgtm

**Pull request merged**
